# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('pod_link', models.CharField(max_length=50)),
                ('img_link', models.CharField(max_length=100)),
            ],
        ),
    ]
